### ISSUE TITLE
On Checkout page is not showing the payment method that was selected

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#38] opened 2021-01-19 13:58 UTC
[![Screenshot_2021-01-19_13-58-45.png](https://mrkr.io/s/6006e595b195ef3b0f138fde/2)](https://mrkr.io/s/6006e595b195ef3b0f138fde/0)

for example:

Your selected Amazon payment method: *1111 (with the CC logo)

so it's more clear which Payment Method was selected

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 434</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment] 2021-01-20 12:59
This is not an issue, it's by design on amazon V2. There's no way of getting info about payment method from the API.

Link [here](https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-checkout/display-shipping-payment-info.html)

Closing.

**Closed by msaggiorato** 2021-01-20 12:59 UTC
Labels: enhancement
