### ISSUE TITLE
(US Region) - Not showing the Billing address as on EU Region

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#43] opened 2021-01-21 13:57 UTC
[![Screenshot_2021-01-21_13-57-07.png](https://mrkr.io/s/60098833b195ef3b0f139b76/2)](https://mrkr.io/s/60098833b195ef3b0f139b76/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ChristianAF** [comment] 2021-01-21 14:14
![image](https://user-images.githubusercontent.com/43881685/105362503-bd7c4180-5bd9-11eb-8e3b-58bf30ad1bfb.png)
with virtual products the billing address is showing

**Comment by msaggiorato** [comment] 2021-01-21 14:42
This is by design on Amazon's side. Non EU region don't get billing address, unless it's the only address you get (eg for digital products). So if you have shipping address, then billing address won't be returned on non EU regions (US for example).

Should we close this as invalid?

**Comment by ChristianAF** [comment] 2021-01-21 18:39
I remember on Customer Support that a US seller complain about having same billing address and shipping address. @msaggiorato

**Comment by msaggiorato** [comment] 2021-01-21 18:41
Yep, that's the same on v1. It's by design on the API side (nothing we can do from the plugin).

**Comment by msaggiorato** [comment] 2021-01-21 19:50
Agreed on Slack DM with @ChristianAF that this is not a bug, but invalid (since the API is like this by design).

**Closed** 2021-01-21 19:50 UTC
Labels: invalid
