### ISSUE TITLE
Billing & Shipping addresses are not showing on the Thank you page

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#40] opened 2021-01-19 15:28 UTC
[![Screenshot_2021-01-19_15-28-01.png](https://mrkr.io/s/6006fa8154855c3154d3f6ef/2)](https://mrkr.io/s/6006fa8154855c3154d3f6ef/0)

Steps to reproduce:

use a Guest user and don't create an account

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6&order-received=61&key=wc_order_daBsiHpfWh5LD](https://stgamazontest.wpengine.com/?page_id=6&order-received=61&key=wc_order_daBsiHpfWh5LD)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment] 2021-01-20 13:04
This is not a bug, it's how WC behaves for guest orders (at least in the latest versions).

https://github.com/woocommerce/woocommerce/blob/master/templates/order/order-details.php#L28

Closing

**Closed** 2021-01-20 13:05 UTC
Labels: invalid
